### ISSUE TITLE
APIView should support HTTP REST APIs 

### ISSUE THREAD

**Issue by JeffreyRichter** [Azure/azure-sdk-tools#2326] opened 2021-11-19 18:49 UTC
For the Azure HTTP API Stewardship Board, it would be wonderful if APIView could take a swagger and convert it to a readable format similar to editor.swagger.io. We'd like the operations sorted together by URL path and then sorted by HTTP methods in this order: POST, PUT, PATCH, GET, DELETE.

It would also be great to be able to compare one version with another version so we can easily see what new operations, query parameters, header, JSON fields, etc. are being introduced/modified in a new swagger to make reviewing of service improvements really easy since we can ignore all that has not changed.

**Comment by tg-msft** [comment] 2021-12-02 01:23
This might be a duplicate of https://github.com/Azure/azure-sdk-tools/issues/2326, except that's less focused on the visual representation

**Closed** 2022-10-17 22:28 UTC
Labels: APIView, Central-EngSys, feature-request, APIView Priority 1
