### ISSUE TITLE
Communication of progress between Azure SDK release planner and sub-apps 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#4538] opened 2022-10-27 19:23 UTC
The Azure SDK Release Planner Beta V2 will navigate to the sub-apps from the Release Planner milestone page.  

- [ ] When task are completed in the sub-app the status should be updated in the Azure SDK Release planner App
- [ ] Milestone status can be determined by how many tasks are complete vs in progress or new 

![image](https://user-images.githubusercontent.com/67656762/198379918-899a0949-0025-43ae-8405-9e576010f766.png)

**Comment by josefree** [comment] 2022-11-23 11:29
we may not follow the float layer design, but for release plan view we can follow

**Comment by josefree** [comment] 2022-11-28 07:04
need to go through details with Crystal

**Comment by josefree** [comment] 2022-12-02 07:07
I wonder this is duplicate of https://github.com/Azure/azure-sdk-tools/issues/4045

**Comment by maririos** [comment] 2023-03-17 19:57
This already happens in the current UI and has been accounted for in the designs @ccbarragan created. Clossing issue

**Closed by maririos** 2023-03-17 19:57 UTC
Labels: Engagement Experience, user study - stakeholder
