### ISSUE TITLE
Version increment tool moves around existing sections in CHANGELOG.md

### ISSUE THREAD

**Issue by Mohit-Chakraborty** [Azure/azure-sdk-tools#1394] opened 2021-02-10 21:43 UTC
We are seeing this behavior in Azure.Search.Documents service area.
Please see this PR as an example of an undesirable update - https://github.com/Azure/azure-sdk-for-net/pull/18670/

**Comment by tg-msft** [comment] 2021-02-10 21:56
We should sort changelog entries by date rather than version because we can pull shenanigans like changing a package name/version, but I can't break spacetime.

**Comment by heaths** [comment] 2021-02-10 22:11
Duplicate of #1389

**Closed by heaths** 2021-02-10 22:11 UTC
Labels: needs-triage
