### ISSUE TITLE
Service name is not being displayed properly in meeting invite...

### ISSUE THREAD

**Issue by markweitzel** [Azure/azure-sdk-tools#3928] opened 2022-08-11 20:38 UTC
For API Stewardship Board Reviews, the invite subject should conform to the following 

```
[<service family> - <service area>] - API Review: <issue #>  
```

**Current State**
![API Review -Cognitive Services • Calendar • markweitzel@microsoft com 2022-08-11 16-33-02](https://user-images.githubusercontent.com/522116/184237208-620f56ef-c349-4fa2-9ea9-f24a6a00607d.png)

**Required State**
![Communication - Telephony Service  #19376 • Calendar • markweitzel@microsoft com 2022-08-11 16-36-41](https://user-images.githubusercontent.com/522116/184237733-63116da9-e6c0-4aba-a676-fbf65d529d87.png)

**Comment by maririos** [comment] 2022-08-17 13:44
Duplicate of https://github.com/Azure/azure-sdk-tools/issues/3948

**Closed by maririos** 2022-08-17 13:44 UTC
Labels: bug, Central-EngSys, Scheduling tool
