### ISSUE TITLE
Epic-product type state does not match service tree current lifecycle stage 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#8456] opened 2024-06-17 16:08 UTC
**Bug/issue:** There are data discrepancy between the epic (product type) State field and the Product Lifecycle Field.  The Service Tree metadata field "Current lifecycle stage" is the value for both of these ADO fields. 

Here is example: 

- Epic product type state = "Closing Down" 
- 
<img width="999" alt="image" src="https://github.com/Azure/azure-sdk-tools/assets/67656762/7235a332-71c6-486c-afe6-225ad3cf1479">

- Service Tree product lifecycle metadata indicates the product lifecycle is "In Development" 
- 
<img width="800" alt="image" src="https://github.com/Azure/azure-sdk-tools/assets/67656762/4a9a17ed-8411-47bd-8102-f531aaecf248">

- Also, I noticed that the Azure SDK bot account made an update on 01/31/2024 to the Data API Builder epic (product type) to update the State, Pub Prev Date, and GADate.  The Product Lifecycle data should have also been changed and has the same value as the State. 

Here is query that can be used to find the data discrepancies that need to be resolved - https://dev.azure.com/azure-sdk/Release/_queries/query/?tempQueryId=31d4fab9-535d-45c4-9b16-7140c8c50f3a 

- [ ] Validate that the Release Planner automation is continuing to validate and sync the service tree lifecycle metadata to ADO.  The state of the epic-product type should be the same as the "Current Lifecycle Stage" in the service tree metadata.

**Comment by praveenkuttappan** [comment] 2024-07-18 14:59
@ladonnaq  We already have automatic synchronization of product's current lifecycle to Product state and Product life cycle fields in work item. I checked the work item in question. It seems you have manually modified the state to `Closing Down` on Fri 3/29/2024 11:01 AM.

I will check few more work items in the query mentioned above.

**Comment by praveenkuttappan** [comment] 2024-08-06 17:58
@ladonnaq   Release planner was earlier getting product metadata from CLC kusto tables. We had made a change few months back to pull the data from service tree tables instead of CLC table and the problem is that this service tree table does not have the current life cycle metadata in some cases. I assume this is something that needs to be updated in the DB by product owner so we will get the data to synchronize it with DevOps work item.  Release planner already has sync state mechanism to ensure that state is synchronized whenever we get the state information from product service tree metadata table.
Metadata is fetched from `DataStudio_ServiceTree_ProductMetadata_Snapshot` table.

**Closed** 2024-08-08 17:15 UTC
Labels: Engagement Experience
