### ISSUE TITLE
Add new Product field into the Informational meeting

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#4250] opened 2022-09-28 19:07 UTC
Currently we are only asking for Service name, but we need to product in order to map the Scheduling tool with the Release Planner App.
We need to make sure:
- Both apps are using the same source for Service Name
- Both apps surface same Product information

**Comment by JonathanCrd** [comment] 2022-11-02 23:14
Question, does the user have to provide both? or just one?

Is the Product Field only visible when the meeting is being scheduled trought the Release Planner app?

**Comment by maririos** [comment] 2022-11-03 03:59
> does the user have to provide both? or just one?

The user will need to provide both. Notice how the products depend on the Service name so we should only surface those. (Release Planner app already does this in case you want to look into that logic).

> Is the Product Field only visible when the meeting is being scheduled trought the Release Planner app?
It should always be visible. @ladonnaq has been thinking in removing the Service Name all together and only show the Product Name. But for now, we should ask/display both

**Comment by JonathanCrd** [comment] 2022-11-08 23:21
Things implemented:

- [x] A new drop down to select the Product has been added.
- [x] Meetings records with the product selected shows it in the disabled product drop down.
- [x] Product information can be passed down from the Planner app into the scheduler (via the draft meeting record).

However, I have questions regarding the following escenarios:

- [ ] Is the Product required when creating a new meeting?
- [ ] Can a user add a Product when editting an existing meeting?
- [ ] What's the expected behavior when a Service Profile does not have a product?

**Comment by maririos** [comment] 2022-11-09 00:20
@ladonnaq could you help with the following questions?:

> -  Is the Product required when creating a new meeting?
> - Can a user add a Product when editting an existing meeting?
> -  What's the expected behavior when a Service Profile does not have a product?

**Comment by maririos** [comment] 2022-11-10 18:13
Should the products present have the same behavior (filtering) as they do in the Release Planner App?
@JonathanCrd to add the specific conditions

**Comment by JonathanCrd** [comment] 2022-11-10 19:22
On the release planner, only the products that fullfill the next condition are shown:
`'Target Lifecycle Stage' = "Private Preview" || 'Target Lifecycle Stage' = "Public Preview" || 'Target Lifecycle Stage' = "GA"`

**Comment by JonathanCrd** [comment] 2022-11-11 00:09
I summarized all of our questions in this follow up issue: https://github.com/Azure/azure-sdk-tools/issues/4682

For now, I'm closing this issue in this release since I have finished added the Product Field and information on the emails.

**Closed by JonathanCrd** 2022-11-11 00:09 UTC
Labels: Central-EngSys, Scheduling tool
