### ISSUE TITLE
Cannot reschedule meeting invite

### ISSUE THREAD

**Issue by peytonfraser** [Azure/azure-sdk-tools#3927] opened 2022-08-11 20:25 UTC
The original invite scheduled for 8/16/2022 at 1p PT. I clicked the link to reschedule to 8/25 at 1p PT, but the link took me to the "new meeting invite" page. When I checked to see the list of meeting invites I created.

I am rescheduling this review for 8/25/2022 at 1p PT.

See recording of bug linked here: https://microsoft-my.sharepoint.com/:v:/p/peytonfraser/ESwIfjceC1BOlymZzsEVNQ0Brg62ddSTgI576wjzuYtC-Q?e=xpXouh

**Comment by peytonfraser** [comment] 2022-08-11 20:26
@markweitzel See issue above

**Comment by maririos** [comment] 2022-08-16 03:32
Thank you @peytonfraser for documenting this and adding the recording. We have addressed the issue and this has been fixed in release `1.0.0-beta.2`

**Closed by maririos** 2022-08-16 03:32 UTC
Labels: needs-triage

**Comment by maririos** [comment] 2022-08-16 03:37
@JonathanCrd  to confirm

**Comment by JonathanCrd** [comment] 2022-08-16 22:07
Confirmed, this was being caused by a bug we were having with the previous version
