### ISSUE TITLE
azure-sdk-for-net PR check in azure-rest-api-specs fails with "permission denied"

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#3162] opened 2022-04-18 17:49 UTC
The azure-sdk-for net PR check is failing in several PRs in the azure-rest-api-specs repo, e.g.

- [# 18174](https://github.com/Azure/azure-rest-api-specs/pull/18174/checks?check_run_id=6031561755)
- [# 18603](https://github.com/Azure/azure-rest-api-specs/pull/18603/checks?check_run_id=6031991775)

<img width="1019" alt="image" src="https://user-images.githubusercontent.com/85643503/163850566-14e192d0-1c83-4b42-99e4-4aedb237ce64.png">

**Comment by akning-ms** [comment] 2022-04-27 03:08
@fengzhou-msft  is working on disable .net SDK track1 generation as there is most of failure caused by SDK testing failure and it will be replaced by .net SDK track 2 generation soon.

**Comment by fengzhou-msft** [comment] 2022-07-04 09:21
> @fengzhou-msft is working on disable .net SDK track1 generation as there is most of failure caused by SDK testing failure and it will be replaced by .net SDK track 2 generation soon.

The first batch is done with https://github.com/Azure/azure-rest-api-specs/pull/18996

The plan is that we will no longer support Track 1 SDK automation from swagger repo once it shipped a corresponding beta/GA version of Track 2 SDK. Service Team can still generate the Track 1 SDK within the azure-sdk-for-net repo and request exception if they want to release a track 1 SDK.

**Comment by fengzhou-msft** [comment] 2022-10-21 08:01
Track 1 SDK generation failure is resolved by downgrading CI agent to Ubuntu 18.04. A long term solution nis tracked by https://github.com/Azure/azure-sdk-for-net/issues/31839

**Closed by fengzhou-msft** 2022-10-21 08:01 UTC
Labels: SDK Automation
