### ISSUE TITLE
Get ApiView Status by ApiView UUID

### ISSUE THREAD

**Issue by dw511214992** [Azure/azure-sdk-tools#4704] opened 2022-11-15 02:45 UTC
We need a rest api to return the apiview’s status by apiview link/id. For example: 
GET https://apiview.dev/AutoReview/GetReviewStatus/Review/881d013952a54321848d7e9b651f4361

**Comment by praveenkuttappan** [comment] 2022-11-21 17:32
This is duplicate of another issue created to track this change. https://github.com/Azure/azure-sdk-tools/issues/4695

**Closed by praveenkuttappan** 2022-11-21 17:32 UTC
Labels: APIView
