### ISSUE TITLE
CrossVersionBreakingChange PR check fails with "Runtime Exception"

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#3273] opened 2022-05-04 15:14 UTC
The CrossVersionBreakingChange PR check for [PR #7087](https://github.com/Azure/azure-rest-api-specs-pr/pull/7087) fails with an obscure "Runtime Exception" message:

<img width="754" alt="image" src="https://user-images.githubusercontent.com/85643503/166712136-6784139a-0145-4d7b-b8c4-bd7ade2f0b31.png">

Here are the details of the failure in the openapi-pipeline-app:

![image](https://user-images.githubusercontent.com/85643503/166713185-7fd413a3-8318-48f8-a8e3-f113dbd1e1a9.png)

**Comment by jianyexi** [comment] 2022-05-09 06:47
It caused by invalid reference in the swagger and the error detail has shown the root cause:  ' ERROR: Referenced file 'file:///mnt/vss/_work/1/azure-rest-api-specs-pr/specification/agrifood/data-plane/Microsoft.AgFoodPlatform/preview/2021-07-31-preview/examples/Models_GetBiomassModelJob.json' not found'

**Comment by jianyexi** [comment] 2022-05-10 01:56
Yeah, because the breaking change tool invokes the 'autorest' and the error message is thrown by autorest, so the the error message was wrapped with 'Command failed' . And this error can be detected by others tools as well, actually we suggest them the fix the validations by this order:
https://github.com/Azure/azure-rest-api-specs-pr/pull/7087#issuecomment-1117282669

**Comment by mikekistler** [comment] 2022-05-10 02:30
I think you are saying that the fix needs to be made in autorest -- is that right?

**Comment by jianyexi** [comment] 2022-05-10 03:24
Currently, the detail message already provided the specific line of the file with invalid refs. But since the output message by autorest is not structural (unfortunately we are relying on autorest v2), it not easy to format it as a human readable message.  Maybe we can show it just as ' failed to resolve refs via autorest , please refer to the log for detail ' ,any thought ?

**Comment by jianyexi** [comment] 2022-05-25 01:32
I created an issue in the tool's repo, maybe we can close it here https://github.com/Azure/openapi-diff/issues/226

**Closed by jianyexi** 2022-05-25 01:32 UTC
Labels: Swagger Tools
