### ISSUE TITLE
[Python] Support overload in APIView

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-tools#3010] opened 2022-03-30 16:21 UTC
Examples:
https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/cognitivelanguage/azure-ai-language-questionanswering/azure/ai/language/questionanswering/aio/_operations/_patch.py

https://github.com/Azure/azure-sdk-for-python/blob/a1d223a38bd4dcc1c36bf57a11185022acee7fa5/sdk/schemaregistry/azure-schemaregistry-avroencoder/azure/schemaregistry/encoder/avroencoder/_schema_registry_avro_encoder.py

https://github.com/Azure/azure-sdk-for-python/blob/e3e8135c83d0ca4cde1aae683b7304cfde39b276/sdk/containerregistry/azure-containerregistry/azure/containerregistry/aio/_async_container_registry_client.py#L573-L587

**Comment by tjprescott** [comment] 2022-04-01 22:12
Duplicate of #3011.

**Comment by tjprescott** [comment] 2022-04-11 19:31
Fixed by https://github.com/Azure/azure-sdk-tools/pull/3044

**Closed by tjprescott** 2022-04-11 19:31 UTC
Labels: APIView, Python
