### ISSUE TITLE
[APIview][Python] Generic type parameter generates with `+` sign

### ISSUE THREAD

**Issue by kristapratico** [Azure/azure-sdk-tools#3840] opened 2022-08-04 20:28 UTC
When subclassing LROPoller with a type parameter, APIVIew generates a `+` sign in the class def:

https://apiview.dev/Assemblies/Review/453e3478565f4bdfb4df7e8ca9b53ba9#7dd8671a22c8489e857e76ffd5f6638a

This occurs with APIView versions 0.3.2 and 0.3.3. It may / may not be related that the methods inherited from LROPoller are also not showing up (i.e. showing as removed in the diff).

**Comment by tjprescott** [comment] 2022-08-05 17:25
This appears to simply be a change in the way that inspect annotates these. Inspect has started prepending either a + or ~ based on whether the inherited type is a covariant or not (+ if yes, ~ if not).

Since this is not a bug in the APIView parsing and conveys accurate information, I will close this issue.

**Closed by tjprescott** 2022-08-05 17:25 UTC
Labels: APIView, Python

**Comment by tjprescott** [comment] 2022-08-05 17:26
This does not have anything to do with why inherited methods have disappeared from the diff. That seems to be an issue with what inspect sees as the namespace for these inherited methods based on whether the APIView is generated on Linux or Windows.
