### ISSUE TITLE
API Docs Preview step failing

### ISSUE THREAD

**Issue by scorpion-ajay** [Azure/azure-sdk-tools#8577] opened 2024-07-09 05:16 UTC
API Docs Preview step failing, also not able to make much sense from the failure logs on the pipeline.

PR: https://github.com/Azure/azure-rest-api-specs/pull/29673

Failure in pipeline causing blocker for SDK release, please help.

![image](https://github.com/Azure/azure-sdk-tools/assets/16050995/40d3bc03-44f6-46c9-af7c-da46d035d77f)

**Comment by nickwalkmsft** [comment] 2024-07-19 20:11
Hi, I'm from the Learn ref docs team.

Our normal intake for these issues is via SitHelp, see [here](https://eng.ms/docs/products/azure-developer-experience/design/api-docs-troubleshooting).

Don't worry about it for this one, I will forward this to our dev team and get back to you here.

**Comment by nickwalkmsft** [comment] 2024-07-19 22:10
The error here isn't the fault of the contents of the PR, it's a problem with the ApiDocPreview build script.

ApiDocPreview uses [utils.getChangedSwaggerFilesInPR](https://devdiv.visualstudio.com/DevDiv/_git/openapi-alps?path=/public/rest-api-specs-scripts/src/utils.ts&version=GBmain&line=644&lineEnd=645&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents) to determine which of the files in the PR are Swaggers so it can submit them for the docs build, but the filtering that method does is insufficient and it sometimes includes files it shouldn't. In this case, the offending file is `sdk-suppressions.yaml` - you can see [here](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3941143&view=logs&j=f06b4322-f7bf-57ee-ecc5-6d0feac67556&t=7af1345c-d4bb-5f1b-a588-9fdc46884407&l=95) in the log that it's been included as a "Swagger" (and in the lines right above that you can see where it's tried to parse the API version from the filename and fails, but it remains the list of "Swaggers" to send to the docs build anyway). When the docs build tries to parse that file as a Swagger spec it fails.

Towards finding a pattern so the filter can be fixed: This appears to be a well-known filename, there's a doc about it [here](https://github.com/Azure/azure-rest-api-specs/blob/09741dc7c9e43a8f9401d782186cac723dc4af71/documentation/sdkautomation/sdk-suppressions.md#next-steps), but I know we saw this same problem recently in another PR (IcM [here](https://portal.microsofticm.com/imp/v3/incidents/incident/512838171/summary)) with a file named `suppressions.yaml` (No `sdk-` prefix).

Re: #8468: the use of the legacy mapping.json build configuration instead of the current reference.config.yml configuration is not the cause of the problem here. Even if you were using reference.config.yml, you'd presumably still be using the same functions within ApiDocPreview to do the same filtering and selection of Swagger specs to submit them for the build.

**Comment by wangyuantao** [comment] 2024-07-25 19:41
https://portal.microsofticm.com/imp/v3/incidents/details/526124359/home

failed on API doc preview block us on security doc fix. See the IcM above. Please prioritize the tool fix. Thanks!

**Comment by nickwalkmsft** [comment] 2024-07-25 20:54
> https://portal.microsofticm.com/imp/v3/incidents/details/526124359/home
> 
> failed on API doc preview block us on security doc fix. See the IcM above. Please prioritize the tool fix. Thanks!

I think this one's actually a slightly different situation - it looks there's both a yaml _and_ a json version of the same Swagger being committed? Both of those are getting sent to the docs build as new swaggers, and the build takes both formats, so every definition is duplicated and you're getting error that usually shows up for that scenario.

I'm not sure what to say about this one, this doesn't appear to be a standard practice in this repo.

Live docs publishing doesn't have this problem because it's only configured to read the json versions.

**Comment by mikeharder** [comment] 2024-07-29 21:35
Fix is to add `suppressions.yaml` and `sdk-suppressions.yaml` to deny-list here:

https://devdiv.visualstudio.com/DevDiv/_git/openapi-alps?path=/public/rest-api-specs-scripts/src/utils.ts&version=GBmain&line=656&lineEnd=657&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents

**Comment by mikeharder** [comment] 2024-07-29 23:04
Fixed in prod:

https://dev.azure.com/devdiv/DevDiv/_git/openapi-alps/pullrequest/568103
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=9960576&view=results

**Closed by mikeharder** 2024-07-29 23:04 UTC
Labels: Central-EngSys
