### ISSUE TITLE
[tsp-client] incompatible-library caused by tsp-client dependencies

### ISSUE THREAD

**Issue by tadelesh** [Azure/azure-sdk-tools#9371] opened 2024-11-13 02:46 UTC
we met an `incompatible-library` warning when using `tsp-client` in sdk automation, see log [here](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4326606&view=logs&j=0303ead4-2e3b-557b-303e-fe8735d4d18f&t=b29b24f0-8be9-5e66-edce-54fd3565c09c).
![Image](https://github.com/user-attachments/assets/c3e6730d-1d2e-484b-a560-ecb0fba1031b). i could only upgrade `tsp-client` version to mitigate it. but in my opinion, tsp-client is a tool to call tsp compile and other command, it should cause typespec dependencies conflict.

**Comment by catalinaperalta** [comment] 2024-11-15 03:08
I believe this is just a warning coming from the `@typespec/compiler` itself and shouldnt affect your code generation. It's not expected that the tsp-client dependencies would match the dependencies for a given spec. I'll look and see if we can somehow just ask it to look in the node_modules under TempTypeSpecFiles/. For context, we do already resolve to the compiler installed under TempTypeSpecFiles/ so the tool is using the expected version: https://github.com/Azure/azure-sdk-tools/blob/816e86402f50a79b4b2f08688c087e1bf9217c9b/tools/tsp-client/src/typespec.ts#L167-L169. You can see that on line 207 from your screenshot.

**Comment by catalinaperalta** [comment] 2024-11-15 04:41
Looks like this is a duplicate of #9346. Closing this issue to track there.

**Closed by catalinaperalta** 2024-11-15 04:41 UTC
Labels: TypeSpec
