### ISSUE TITLE
Add Milestones graph to summary screen

### ISSUE THREAD

**Issue by JonathanCrd** [Azure/azure-sdk-tools#6371] opened 2023-06-20 00:46 UTC
Add a snapshot or preview of the milestones in the summary screen for the Release Plan.

We should follow the new UI design in Figma.

**Comment by maririos** [comment] 2023-08-10 17:10
Duplicate of https://github.com/Azure/azure-sdk-tools/issues/6747

**Closed by maririos** 2023-08-10 17:10 UTC
Labels: Central-EngSys, Engagement Experience
