### ISSUE TITLE
Use pre-installed Az PowerShell module rather than downloading from PSGallery

### ISSUE THREAD

**Issue by mitchdenny** [Azure/azure-sdk-tools#1089] opened 2020-10-13 03:04 UTC
To help improve the performance and reliability of our builds we want to rely on the pre-installed version of Az PowerShell as much as possible in our build pipelines. What we are thinking here is that teams that have pipelines that require a newer version of a Cmdlet can optionally specify an up-level version of the module and their specific pipeline can download it, otherwise they'll take the default that is baked into the underlying image.

The overriding version will have to be strictly newer, so if the version specified is down-level it won't be used. This is to protect our pipelines from bit-rotting on old unsupported versions of Az PowerShell.

**Comment by weshaggard** [comment] 2020-10-16 18:35
duplicate of https://github.com/Azure/azure-sdk-tools/issues/1051

**Closed by weshaggard** 2020-10-16 18:35 UTC
Labels: needs-triage
