### ISSUE TITLE
TypeSpec Validation result reporting

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#6231] opened 2023-05-24 18:50 UTC
Is it correct for the job to fail when there are `warnings` in the `chuchu` job?

Example: https://github.com/Azure/azure-rest-api-specs-pr/pull/12045/checks?check_run_id=13252511527

![image](https://github.com/Azure/azure-sdk-tools/assets/9868623/6f1ffeb0-b9d4-4f1d-8586-8143120123ca)

**Comment by mikeharder** [comment] 2023-05-24 19:40
@maririos: Are you asking if it's by design that TypeSpecValidation **fails** when the TypeSpec compiler emits **warnings**?  If so, I believe the answer is "yes", for two reasons:

1. The TypeSpecValidation tool was implemented this way before ownership was transferred, so I assume this was the desired behavior.
2. We want to keep all specs in our repos as clean as possible (no compiler warnings, formatted using `tsp format`, etc)

In this scenario, I think the spec author should fix the warnings before the PR is merged.

**Closed** 2023-05-24 20:03 UTC
Labels: Central-EngSys, Spec PR Tools
