### ISSUE TITLE
[Swift APIView] Add tests to Swift APIView and CI

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-sdk-tools#2325] opened 2021-11-19 18:21 UTC
Work item for MQ:
- [ ] Add unit tests to Swift APIView
<del>- [ ] Add pipeline stage to APIView pipelines</del>
<del>  - [ ] build</del>
<del>  - [ ] run tests</del>

**Comment by tjprescott** [comment] 2022-01-11 18:02
CI-related items will be tracked under https://github.com/Azure/azure-sdk-tools/issues/2532

**Comment by tjprescott** [comment] 2022-01-11 18:03
CI-related items will be tracked under https://github.com/Azure/azure-sdk-tools/issues/2532

**Comment by kyle-patterson** [comment] 2024-10-09 20:22
Closing as duplicate of #2532

**Closed by kyle-patterson** 2024-10-09 20:22 UTC
Labels: APIView, Client, MQ, APIView Priority 1, Swift
