### ISSUE TITLE
Add Readme linter for ci validaiton

### ISSUE THREAD

**Issue by sima-zhu** [Azure/azure-sdk-tools#3424] opened 2022-06-09 20:48 UTC
Docs team scan through the all files on docs.ms review site. 
There are certain amount of issues are from our language repo readme.
We currently depends their vendor resources to clear the existing issues.
We'd better to introduce the same linter tool to avoid future problems.

AI:
Will talk to docs team if they have any tool or API to use for validation.

**Comment by kurtzeborn** [comment] 2023-02-13 21:52
Dupe of https://github.com/Azure/azure-sdk/issues/1698

**Closed by kurtzeborn** 2023-02-13 21:52 UTC
Labels: Docs, Central-EngSys
