### ISSUE TITLE
API Health Check in Management Plane API readiness 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#7060] opened 2023-10-03 13:01 UTC
I was working with a new service, which just completed naming approval for their new service and offering.  They ran API readiness on the pull request (before it was merged) and it was failing the API Health Check that shows up on the signoff screen only.  

- [ ] Is API Health Check the same as API Readiness check in the PR?  If so, we should run this earlier and direct team to error messages so they can correct?  
- [ ] I noticed that API readiness check failed, and the PR was still merged.  What is the check and why would a PR merge if a check failed?  https://github.com/Azure/azure-rest-api-specs/pull/24798/checks?check_run_id=15436017902

![image](https://github.com/Azure/azure-sdk-tools/assets/67656762/2eddcf14-74f3-43be-a77d-727e4b0eda1c)

**Comment by maririos** [comment] 2023-10-06 18:14
>  Is API Health Check the same as API Readiness check in the PR? 

@praveenkuttappan  can you confirm this?

> If so, we should run this earlier and direct team to error messages so they can correct?

@ladonnaq where would you move this check to?

> I noticed that API readiness check failed, and the PR was still merged. What is the check and why would a PR merge if a check failed? https://github.com/Azure/azure-rest-api-specs/pull/24798/checks?check_run_id=15436017902

You would have to ask the ARM reviewer on why they approved and merged even with that failure. There is no message or description in the PR that talks about it.
I see that the `Complete` button is still enabled, which makes me think that it is not a problem.... but @praveenkuttappan  to confirm here too on the requirement of this pipeline result

**Comment by maririos** [comment] 2023-12-04 20:43
ping @praveenkuttappan

**Comment by praveenkuttappan** [comment] 2024-02-01 16:09
That's correct/ It's API readiness check. None of the failure status will block completing a release plan if PR is ready to merge. Release plan completion only relies on PR mergeable status. If we plan to remove all these validation statuses to keep it simple and just show link to PR and PR's mergeable status, then we can simplify this final summary screen.

**Comment by maririos** [comment] 2024-02-01 21:54
I am going to close this issue as by design

**Closed by maririos** 2024-02-01 21:54 UTC
Labels: Engagement Experience
