### ISSUE TITLE
Swagger Breaking Changes PR check fails with "command failed"

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#3122] opened 2022-04-11 21:25 UTC
The Swagger Breaking Changes PR check in [PR #18174](https://github.com/Azure/azure-rest-api-specs/pull/18174) fails with a really strange error message:
```
"details":"Command failed: node /mnt/vss/_work/_tasks/AzureApiValidation_5654d05d-82c1-48da-ad8f-161b817f6d41/0.0.27...
```

I re-ran the PR pipeline with `/azp run` and got the same error, so does not appear to be a transient issue.

Here's a link to the full results in ADO: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1496495&view=logs&j=98f87804-8e1f-5655-af02-e80aefa7aa97&t=65457206-7ab6-5966-2a2f-9ae3efa14a03

**Comment by jianyexi** [comment] 2022-04-27 04:02
it was caused by the invalid swagger example and already been fixed in the PR
https://github.com/Azure/azure-rest-api-specs/blob/b3c76f6891f5d98250783fec3f1629fdab50101b/specification/cost-management/resource-manager/Microsoft.CostManagement/stable/2021-10-01/examples/Operations.json

**Comment by mikekistler** [comment] 2022-04-27 12:18
I have reopened this issue because I think our tooling should be resilient to buggy swagger examples.

**Comment by jianyexi** [comment] 2022-04-28 02:25
Sorry, do you mean to have friendly diagnostic message?

**Comment by jianyexi** [comment] 2022-05-25 01:33
seems it's also about error message, create a unified issue to do such stuff

**Closed by jianyexi** 2022-05-25 01:33 UTC
Labels: Swagger Tools
