### ISSUE TITLE
[LintDiff] LintDiff CI fails when only warning exists, is it by design?

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/azure-sdk-tools#8165] opened 2024-04-28 01:56 UTC
CI https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3735740&view=logs&j=0574a2a6-2d0a-5ec6-40e4-4c6e2f70bea2&t=80c3e782-49f0-5d1c-70dd-cbee57bdd0c7

The Swagger LintDiff only have warning. But the LintDiff still report failure. My understanding is that only error would fail the LintDiff.

Also, I remember saw it fail when there is no warning (and no error).

**Comment by kurtzeborn** [comment] 2024-04-29 20:55
Not sure if this should go to ARM or Konrad.  Please re-route as appropriate.

**Comment by konrad-jamrozik** [comment] 2024-04-30 21:31
LintDiff has failed:

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3735740&view=logs&j=0574a2a6-2d0a-5ec6-40e4-4c6e2f70bea2&t=80c3e782-49f0-5d1c-70dd-cbee57bdd0c7&l=859

> Execution of AutoRest with LintDiff done. Error is not null: true, stdout contains AutoRest 'error': true, stdout contains AutoRest 'fatal': true, stderr contains AutoRest 'error': false, stderr contains AutoRest 'fatal': false
> RETURN definition momentOfTruth.executeAutoRestWithLintDiff.

> {"level":"fatal","message":"Process() cancelled due to failure "}
> {"level":"error","message":"!Error: There are multiple operations defined for \n  'get: /sentShares'.\n\n  You are probably trying to use an input with multiple API versions with an autorest V2 generator, and that will not work. "}
> {"level":"error","message":"Autorest completed with an error. If you think the error message is unclear, or is a bug, please declare an issues at https://github.com/Azure/autorest/issues with the error message you are seeing."}

Closing this as duplicate of:
- https://github.com/Azure/azure-sdk-tools/issues/8169

**Closed by konrad-jamrozik** 2024-04-30 21:31 UTC
Labels: Central-EngSys

**Comment by weidongxu-microsoft** [comment] 2024-05-06 06:11
Thanks @konrad-jamrozik 

A quick confirmation. Do you mean this AutoRest error?
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3735740&view=logs&j=0574a2a6-2d0a-5ec6-40e4-4c6e2f70bea2&t=80c3e782-49f0-5d1c-70dd-cbee57bdd0c7&l=105668

```
[
  {
    "type": "AutoRest exception",
    "message": "Process() cancelled due to failure",
    "readmeUrl": "[https://github.com/Azure/azure-rest-api-specs/blob/main/specification/purview/data-plane/readme.md",](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/purview/data-plane/readme.md%22,)
    "tag": "default",
    "context": "before"
  },
  {
    "type": "AutoRest exception",
    "message": "!Error: There are multiple operations defined for   'get: /sentShares'.  You are probably trying to use an input with multiple API versions with an autorest V2 generator, and that will not work.",
    "readmeUrl": "[https://github.com/Azure/azure-rest-api-specs/blob/main/specification/purview/data-plane/readme.md",](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/purview/data-plane/readme.md%22,)
    "tag": "default",
    "context": "before"
  },
  {
    "type": "AutoRest exception",
    "message": "Autorest completed with an error. If you think the error message is unclear, or is a bug, please declare an issues at https://github.com/Azure/autorest/issues with the error message you are seeing.",
    "readmeUrl": "[https://github.com/Azure/azure-rest-api-specs/blob/main/specification/purview/data-plane/readme.md",](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/purview/data-plane/readme.md%22,)
    "tag": "default",
    "context": "before"
  }
]
```

**Comment by konrad-jamrozik** [comment] 2024-05-06 21:34
@weidongxu-microsoft you wrote:

> The Swagger LintDiff only have warning. But the LintDiff still report failure.

This is an issue with results truncation: the GitHub check page only shows warnings because it truncates the full report. The full report has the `AutoRest exception`. See the issue I linked for details.
