### ISSUE TITLE
[PR Workflow] Bot injection of text when TypeSpec usage warning/error is generated

### ISSUE THREAD

**Issue by MattGertz** [Azure/azure-sdk-tools#7542] opened 2024-01-17 18:49 UTC
When the build process detects that TypeSpec was not used in the generation of OpenAPI, could we auto-insert the following markdown text (or similar) inserted into the PR:

> ~~This is a follow-up to provide context for the TypeSpec Requirement warning generated for this PR.  For more information on this requirement, please see [Azure SDK documentation (eng.ms)](https://eng.ms/docs/products/azure-developer-experience).  If you believe that the ARM board approved an exception in this case, please contact ARM & **typespeconboard** with the relevant documentation so that we can close on this.  Thanks!~~

> ~~TypeSpec usage is required for all new (greenfields) services.  This is currently enforced as a warning, but will made a blocking error in the future.  Refer to \[Azure SDK documentation (eng.ms)\](https://eng.ms/docs/products/azure-developer-experience) for more information on addresing this, and contact ARM/**typespeconboard** for any questions.~~

> TypeSpec usage is required for all new (greenfields) services.  This is currently enforced as a warning, but will be made a blocking error in the future.  Please refer questions about this policy to \[RP Help](https://aka.ms/rphelp).  For information on  converting from OpenAPI to TypeSpec, refer to \[Azure SDK documentation (eng.ms)\](https://eng.ms/docs/products/azure-developer-experience).

(post edited by @konrad-jamrozik)
(post edited by @MattGertz)

**Comment by MattGertz** [comment] 2024-01-17 18:50
(Ah, and of course, the markdown was converted when I submitted this, d'oh...)

**Comment by konrad-jamrozik** [comment] 2024-01-17 19:22
From technical standpoint I can propose the following:

We already have logic that obtains required GitHub checks, see [`getGraphQLQuery`](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/openapi-alps?path=private/openapi-kebab/src/bots/pipeline/pipelineEventListener/getRequiredCheckRuns.ts&version=GCa0b6fac2fa92c17ce2fe394068a3ae9cd6e5a2bd&line=78&lineStartColumn=10&lineEndColumn=25&_a=contents) called from [`getRequiredAndAutomatedMergingRequirementsMetCheckRuns`](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/openapi-alps?path=private/openapi-kebab/src/bots/pipeline/pipelineEventListener/getRequiredCheckRuns.ts&version=GCa0b6fac2fa92c17ce2fe394068a3ae9cd6e5a2bd&line=13&lineStartColumn=23&lineEndColumn=77&_a=contents). This is used to populate the `Next Steps to Merge` comment via [`buildNextStepsToMergeCommentBody`](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/openapi-alps?path=private/openapi-kebab/src/bots/pipeline/pipelineEventListener/renderNextStepsToMerge.ts&version=GC7c0a62edaeb30e0c0363307b6c5f0484f0631c1e&line=28&lineStartColumn=16&lineEndColumn=48&_a=contents). This happens both upon next CI pipeline run e.g. due to commit push, via [`renderUnifiedPipelineRunEvent`](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/openapi-alps?path=private/openapi-kebab/src/bots/pipeline/pipelineEventListener/PipelineEventListener.ts&version=GC0e4e2be3c5230ca4b09cef141d02de098150afbb&line=351&lineStartColumn=17&lineEndColumn=46&_a=contents) as well as in reaction to a labelling event, via [`processBotUpdateEvent`](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/openapi-alps?path=private/openapi-kebab/src/bots/pipeline/pipelineEventListener/PipelineEventListener.ts&version=GC0e4e2be3c5230ca4b09cef141d02de098150afbb&line=245&lineStartColumn=17&lineEndColumn=38&_a=contents).

We could inject extra logic in [`buildNextStepsToMergeCommentBody`](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/openapi-alps?path=private/openapi-kebab/src/bots/pipeline/pipelineEventListener/renderNextStepsToMerge.ts&version=GC7c0a62edaeb30e0c0363307b6c5f0484f0631c1e&line=28&lineStartColumn=16&lineEndColumn=48&_a=contents) or somewhere in the relevant call chain to make the `Next Steps to Merge` comment provide extra information. We could read the status of `TypeSpec Requirement` and `TypeSpec Validation` checks (adapt the code from `getGraphQLQuery`) to read failed GitHub checks even if they are not marked as `required` on GitHub.

Some other code that could be possibly relevant here:

- Our `pipeline-bot` has a callback on any label addition, due to [`[PullRequest.labeled]: this.pullRequestLabeled`](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/openapi-alps?path=private/openapi-kebab/src/bots/pipeline/pipelineBot.ts&version=GC9b093117d2bb0d2e879b20de8394807646bb57e5&line=41&lineStartColumn=7&lineEndColumn=54&_a=contents). Some of it is processed [`processBotUpdateEvent`](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/openapi-alps?path=private/openapi-kebab/src/bots/pipeline/pipelineEventListener/PipelineEventListener.ts&version=GC0e4e2be3c5230ca4b09cef141d02de098150afbb&line=245&lineStartColumn=17&lineEndColumn=38&_a=contents). We could inject some logic based on addition of some labels like `TypeSpecRequried` or `TypeSpecInvalid`. But then we would need to ensure to revert the changes (remove or add another label, update comment) once TypeSpec problems are fixed / suppressed.

@weshaggard @mikeharder thoughts?

@MattGertz this is a new / special case for our codebase so it is going to take few days of implementation work until we can deploy it.

**Comment by MattGertz** [comment] 2024-01-17 19:48
Thanks @konrad-jamrozik!  I want to keep it generic, if that's OK -- that way, we can update the text in the link instead to correspond to blocking/not blocking state, saving a step.  (This will also help us later when brownfields becomes relevant.

Thanks for the cost numbers also -- lemme know when it ends up in a sprint, and I'll keep partners informed.

**Comment by konrad-jamrozik** [comment] 2024-01-17 21:32
> Thanks @konrad-jamrozik! I want to keep it generic, if that's OK -- that way, we can update the text in the link instead to correspond to blocking/not blocking state, saving a step. (This will also help us later when brownfields becomes relevant.)
> 
> Thanks for the cost numbers also -- lemme know when it ends up in a sprint, and I'll keep partners informed.

@MattGertz the PR review process is complex (see [the diagram](https://aka.ms/azsdk/pr-diagram)) and creates a lot of support burden for us (AzSDK EngSys team, ARM team, breaking change review board, SDK team). Hence we strive for clarity. Given that, I believe the message should be explicit about if the problem is a blocker or just a warning. Both the `Next Steps to Merge` comment and `automated merging requirements met` check are already clearly communicating what is blocking and what is not. Once we add this info about TypeSpec, we should follow that convention. The extra work to ensure this distinction won't be that significant.

**Comment by MattGertz** [comment] 2024-01-17 22:04
Got it @konrad-jamrozik .  So, let's go with the current wording to start, and then I will file a bug to request that the word "warning" be changed to "blocking error" when we flip the bit on it.

**Comment by MattGertz** [comment] 2024-01-17 22:10
Exchanged mail with Mike.  I'm going to edit the OP to align the text with the "Next Steps" suggestion he made.

**Comment by konrad-jamrozik** [comment] 2024-01-17 22:59
Btw how to interpret this:

> and contact ARM/typespeconboard for any questions.

?

Is this an email alias? Teams channel?

**Comment by rkmanda** [comment] 2024-01-19 19:59
@MattGertz I was assuming that we discover through automation that the PR being raised is for a new service and show the message only when that condition is satisfied. I do not see a mention of this in Konrad's technical analysis. Can someone clarify?

**Comment by konrad-jamrozik** [comment] 2024-01-20 00:33
> I was assuming that we discover through automation that the PR being raised is for a new service and show the message only when that condition is satisfied. I do not see a mention of this in Konrad's technical analysis. Can someone clarify?

@rkmanda the overall idea is as follows:

- For "greenfield" specs we require the usage of TypeSpec. The automation will detect if this requirement is violated and add relevant info to the `Next Steps to Merge` comment and `Automated merging requirements met` check. We also mention this all over the place at https://aka.ms/azsdkdocs.
- As of 1/19/2024 this is just a warning, but within weeks we will change this into a merge blocker.
- Even so, this is a last resort measure. PR authors should have been informed about this requirement long before they tried to submit a PR that violates it.

Copy-pasting @mikeharder's explanation from the email thread on how we define a "greenfield" spec:

> The heuristic we are currently using is simple.  A service is "brownfield" if and only if it contains > a "stable" folder in public/main.  Else, the service is "greenfield".
> 
> Overall, the check will work as follows:
> 1.	Identify all OpenAPI files (*.json) added or changed in a PR
> 2.	For each OpenAPI file
> 		a.	If TypeSpecRequirement is suppressed, continue
> 		b.	If OpenAPI contains x-typespec-generated, continue (spec is using TypeSpec)
> 		c.	If spec folder in public/main contains "stable" folder, continue (spec is brownfield)
> 		d.	Else, show error (spec appears to be "greenfield" but OpenAPI was not generated from TypeSpec)
> 3.	If any OpenAPI files caused errors
> 		a.	Fail check (which will block merging)
> 		b.	Show message in "Next Steps to Merge"
> 
> If a PR is idenitified as brownfield ("stable" folder in public/main), or a greenfield using TypeSpec, > the check passes and no message is shown.

**Comment by josefree** [comment] 2024-01-22 02:01
The method “A service is "brownfield" if and only if it contains a "stable" folder in public/main” could have a leak as [Service Tree | Products | Azure Storage Actions (microsoftservicetree.com)](https://microsoftservicetree.com/products/739ccd98-1d9f-43e1-b334-448079cc0481/metadata/Lifecycle%20Status).  Currently, Storage Actions is private preview, heading to public preview.  However, it has published only a stable version https://github.com/Azure/azure-rest-api-specs/tree/main/specification/storageactions/resource-manager/Microsoft.StorageActions/stable/2023-01-01.   Storage Actions should not be treated as a brownfield, right?

**Comment by mikeharder** [comment] 2024-01-23 06:56
> The method “A service is "brownfield" if and only if it contains a "stable" folder in public/main” could have a leak as [Service Tree | Products | Azure Storage Actions (microsoftservicetree.com)](https://microsoftservicetree.com/products/739ccd98-1d9f-43e1-b334-448079cc0481/metadata/Lifecycle%20Status). Currently, Storage Actions is private preview, heading to public preview. However, it has published only a stable version https://github.com/Azure/azure-rest-api-specs/tree/main/specification/storageactions/resource-manager/Microsoft.StorageActions/stable/2023-01-01. Storage Actions should not be treated as a brownfield, right?

Tracking this feedback separately at https://github.com/Azure/azure-rest-api-specs-pr/issues/16733

**Comment by maririos** [comment] 2024-01-24 00:59
@MattGertz Looking at the text that will be included, I worry that it is ARM specific but the check, if I am not wrong, applies to data plane too. Is this temporary and we are going to have a doc for data plane?

**Comment by konrad-jamrozik** [comment] 2024-01-25 00:58
[Pull Request 523770](https://devdiv.visualstudio.com/DevDiv/_git/openapi-alps/pullrequest/523770): Add support for 'FYI' GitHub checks + add 'TypeSpec Requirement' check as FYI

**Comment by konrad-jamrozik** [comment] 2024-01-25 22:36
@maririos per further discussion we had, the check will apply both to ARM and data-plane. We also updated the check text.

**Comment by maririos** [comment] 2024-01-30 22:18
> @maririos per further discussion we had, the check will apply both to ARM and data-plane. We also updated the check text. See [Pull Request 523770](https://devdiv.visualstudio.com/DevDiv/_git/openapi-alps/pullrequest/523770).

I saw it live today and looks great. Thank you for the change :)

**Closed** 2024-01-30 22:22 UTC
Labels: Central-EngSys, Spec PR Tools
