### ISSUE TITLE
autorest.testmodeler only install on Node 18

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-tools#5183] opened 2023-01-20 23:39 UTC
After quick investigation, it pulls oav 3.0.3 that pulls yasmay that now pulls Node18 only dependencies.

Fix could be moving to oav 3.3.0 ([since 3.2.0 yasmay has been removed](https://github.com/Azure/oav/pull/860))

We're not ready to force customers of autorest to be on Node 18 at this point

**Comment by mikeharder** [comment] 2023-01-21 07:47
The issue is not package `yasway`.  `yasway` depends on `json-schema-ref-parser`, not to be confused with `@apidevtools/json-schema-ref-parser`.

This issue is the combination of two problems.

First, `@apidevtools/json-schema-ref-parser` accidentally shipped a breaking change in version `9.1.1`  to require `"engines": { "node": ">= 17" }` (https://github.com/APIDevTools/json-schema-ref-parser/issues/298).

However, `@autorest/testmodeler` includes an `npm-shrinkwrap.json` that pins `@apidevtools/json-schema-ref-parser` to `9.0.9`, so this shouldn't be a problem:

```
$ nvm use 16.6.2
Now using node v16.6.2 (npm v7.20.3)

$ npm install @autorest/testmodeler@2.4.0

$ npm ls @apidevtools/json-schema-ref-parser
└─┬ @autorest/testmodeler@2.4.0
  └─┬ oav@3.0.3
    └─┬ swagger-parser@10.0.3
      └─┬ @apidevtools/swagger-parser@10.0.3
        └── @apidevtools/json-schema-ref-parser@9.0.9
```

However, I believe `autorest` installs extension packages using `yarn` instead of `npm`.  And `yarn` ignores `npm-shrinkwrap.json` inside packages (https://github.com/yarnpkg/yarn/issues/838).

```
$ yarn add @autorest/testmodeler@2.4.0
yarn add v1.22.19
...
error @apidevtools/json-schema-ref-parser@9.1.1: The engine "node" is incompatible with this module. Expected version ">= 17". Got "16.6.2"
```

If `autorest` wants to allow extensions to pin their dependencies using `npm-shrinkwrap.json` (which seems like a good thing), it will need to install them using `npm` instead of `yarn`.

**Comment by mikeharder** [comment] 2023-01-21 08:24
Upgrading to the latest version of `oav` would not fix the issue, and in fact there is an unrelated breaking change in `oav@3.2.3` (https://github.com/Azure/oav/issues/949).

If `oav` fixes both https://github.com/Azure/oav/issues/949 and https://github.com/Azure/oav/issues/950, then upgrading to the latest version of `oav` would have prevented this issue, since `@apidevtools/swagger-parser@10.1.0` pins the version of `@apidevtools/json-schema-ref-parser`.

However, we cannot count on our dependencies to pin all of their dependencies (transitively), so the only solution is a lockfile that is respected when the package is installed.

**Comment by mikeharder** [comment] 2023-01-24 01:46
A possible workaround might be adding the following to https://github.com/Azure/azure-sdk-tools/blob/main/tools/sdk-testgen/packages/autorest.testmodeler/package.json:

```
"overrides": {
    "@apidevtools/json-schema-ref-parser": "9.0.9"
},
"resolutions": {
    "@apidevtools/json-schema-ref-parser": "9.0.9"
}
```

These sections provides hints to npm (`overrides`) and yarn (`resolutions`) regarding which versions of transitive deps to use.

I verified this works when running `yarn install` locally in folder `tools/sdk-testgen/packages/autorest.testmodeler`, but I'm not sure if it will work when the package is published and installed by `yarn` from `npmjs.com`.

**Comment by mikeharder** [comment] 2023-01-25 02:18
Unfortunately, adding `overrides` and `resolutions` to `package.json` does not help when `yarn` is consuming the published package tarball, so I don't think this workaround will help.

**Comment by mikeharder** [comment] 2023-01-25 18:47
Closing since https://github.com/APIDevTools/json-schema-ref-parser/issues/298 has been fixed in `@apidevtools/json-schema-ref-parser@9.1.2`

**Closed by mikeharder** 2023-01-25 18:47 UTC
Labels: Swagger Tools
