### ISSUE TITLE
Swagger APIView does not seem to follow external refs

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#6259] opened 2023-05-30 21:20 UTC
In [PR 23804](https://github.com/Azure/azure-rest-api-specs/pull/23804), the schema for the default error response references a schema in a "common-types" file.
```json
    "CommunicationErrorResponse": {
      "$ref": "../../../Common/stable/2021-03-07/common.json#/definitions/CommunicationErrorResponse"
    },
```

But the details for the schema are not shown in the APIView:

<img width="777" alt="image" src="https://github.com/Azure/azure-sdk-tools/assets/85643503/26101b94-1de6-4793-a6bf-73707e4a4c1f">

**Comment by chidozieononiwu** [comment] 2023-05-31 01:29
duplicate of https://github.com/Azure/azure-sdk-tools/issues/6008
will have this resolved by the next release.

**Closed** 2023-06-27 20:10 UTC
Labels: APIView, Central-EngSys
