### ISSUE TITLE
[typespec-validation] Checks don't fail if there are no swagger specs for a TypeSpec PR

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-tools#7517] opened 2024-01-12 00:52 UTC
The REST API Stewardship board saw [a PR](https://github.com/Azure/azure-rest-api-specs-pr/pull/16269) that correctly caught there was no `readme.md` in the TypeSpec changes, but did not catch that the generated swaggers were not included. Validation should catch when there are no updated swaggers.

**Comment by mikeharder** [comment] 2024-01-18 01:34
@heaths: Can you be more specific about the invalid state you think TypeSpecValidation fails to detect?  Is there a specific commit in https://github.com/Azure/azure-rest-api-specs-pr/pull/16269 that shows the problem?

For the latest commit `03c53f8`, TypeSpecValidation fails with this error:

```
Rule FolderStructure failed
Invalid folder structure. Package must contain main.tsp or client.tsp, tspconfig.yaml,
and examples folder if there's main.tsp.
```

While this error message could be more helpful (e.g. provide a link to https://github.com/Azure/azure-rest-api-specs/blob/main/documentation/typespec-structure-guidelines.md), the check is correctly identifying the problem.

If these errors were fixed, but the generated OpenAPI files were still missing, TypeSpecValidation should still fail, because the `GitDiff` rule should detect added files.

**Comment by heaths** [comment] 2024-01-18 22:52
Swaggers should be committed to the repo along with the typespecs. That's our understanding, anyway. Seems no validation is checking that swaggers are included i.e., those emitted from the autorest emitter. We still want those included to support third parties - or even first parties that need OpenAPI v2.

**Comment by mikeharder** [comment] 2024-01-18 23:00
> Seems no validation is checking that swaggers are included i.e., those emitted from the autorest emitter

The check should be catching this.  If you don't think it is, please share an example I can use to repro.

**Comment by heaths** [comment] 2024-01-19 22:14
I did. It's linked in my OP, and copied here: <https://github.com/Azure/azure-rest-api-specs-pr/pull/16269>

**Comment by mikeharder** [comment] 2024-01-19 22:18
I don't see how this PR (at current commit `0a4c471e`) is reproducing the problem you say it does.  TSV is failing in the `FolderStructure` rule.  So the check is catching the problem.

**Comment by heaths** [comment] 2024-01-19 22:52
It doesn't flag that no swaggers were found, though. Are you saying we only run one validation at a time and fail fast? Seems we should try to log as many validation failures as possible like compilers would do, lest a long inner dev loop and tons of commits that, as a review, get really annoying when you aren't sure if they are "done" or not.

Or are you saying that, because the folder structure is wrong, it's like a compiler error that is terminal to finding all other errors?

**Comment by mikeharder** [comment] 2024-01-20 00:16
I understand our disconnect now.  Currently, TypeSpec Validation fails fast after the first rule that fails:

https://github.com/Azure/azure-rest-api-specs/blob/0a29f9763e50adf092908d090ae4b91037bdc3e7/eng/tools/typespec-validation/src/index.ts#L54-L56

I agree that ideally TSV would try to show as many errors as possible like compilers.  However, I'm afraid this might add significant complexity to the tool, and ultimately confuse users more than help.

For example, if your folder structure is wrong, is it really worth it for us to even try compiling your TypeSpec?  In which directory?

The way TSV is currently written, later rules can assume earlier rules passed, which simplifies things greatly.  For example, once rule `FolderStructure` has passed, later rules can assume (for example) that file `tspconfig.yaml` exists in the correct location, and don't need to handle errors.

Another reason I think this is less important for TSV, is that some of the sub-tasks executed by TSV (tsp compiler and linter) do show as many errors as possible.  The rules implemented directly in TSV (FolderStructure, NpmPrefix, LinterRuleset, etc) are relatively simple and shouldn't require a lot of iterations to get clean.  What usually requires the most iteration are tsp compiler and linter errors.

Regarding the dev inner loop, we have made it very easy to run TSV locally on your dev machine.  Once spec authors see a failure of TSV in their PR, they can run TSV locally to iterate until all issues are fixed.

**Comment by heaths** [comment] 2024-01-22 22:11
> For example, if your folder structure is wrong, is it really worth it for us to even try compiling your TypeSpec? In which directory?

No, I don't think so. That's what made me ponder if this was more like a terminal compiler error in much the same way you mention: can't find / assume structure about files.

Still, in general, it may be worth considering. As many validators (or even compilers), they just keep pumping issues to stdout (and/or elsewhere). It may be easy to run it locally, but I think experience has taught us people won't. Perhaps an output message (like a footer or something to any terminal error) could give them the command line, though. Experience has taught me that many won't go into AzDO to actually find the command line and some tasks - though I don't think this one is a problem - seem to go out of their way to hide the command line they run.

**Comment by mikeharder** [comment] 2024-04-01 18:50
Won't fix until we get more feedback from spec authors this is impacting their productivity

**Closed by mikeharder** 2024-04-01 18:50 UTC
Labels: Spec PR Tools
