### ISSUE TITLE
Swagger APIView should always override APIView link result in spec PR pipeline.

### ISSUE THREAD

**Issue by ruowan** [Azure/azure-sdk-tools#5458] opened 2023-02-15 07:01 UTC
To make swagger APIView user experience consistent,  Swagger APIView should always override APIView with the latest artifact.  Or add a parameters of md5 for APIView token content. Make sure the latest APIView artifact is displayed in APIView.

**Comment by mikekistler** [comment] 2023-02-23 22:57
@praveenkuttappan pls mark as dup if you have already addressed this issue.

**Comment by praveenkuttappan** [comment] 2023-02-28 22:01
Duplicate of https://github.com/Azure/azure-sdk-tools/issues/5468

**Closed** 2023-02-28 22:01 UTC
Labels: APIView
