### ISSUE TITLE
Notification creator should clean up stale notification teams

### ISSUE THREAD

**Issue by benbp** [Azure/azure-sdk-tools#2631] opened 2022-01-26 23:11 UTC
The notification creator tool and pipeline should delete devops teams for pipelines that no longer exist.

**Comment by weshaggard** [comment] 2022-01-26 23:48
Looks to be a duplicate of https://github.com/Azure/azure-sdk-tools/issues/124.

**Closed** 2022-01-27 21:33 UTC
Labels: needs-triage
