### ISSUE TITLE
[Test-Proxy] URI doesn't match on playback

### ISSUE THREAD

**Issue by kristapratico** [Azure/azure-sdk-tools#2262] opened 2021-11-12 18:49 UTC
I recorded a test using the test proxy and upon running on playback I'm getting an "InternalServerError" with this message in the logs:

```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]

An unhandled exception has occurred while executing the request.

Azure.Sdk.Tools.TestProxy.Common.TestRecordingMismatchException: Unable to find a record for the request POST https://text/analytics/v3.2-preview.2/languages?showStats=true

Uri doesn't match:

request <https://text/analytics/v3.2-preview.2/languages?showStats=true>

record <https://fakeendpoint.cognitiveservices.azure.com/text/analytics/v3.2-preview.2/languages?showStats=true>

Header differences:

Body differences:
```

It looks like the base URL is not expected when running in playback.

PR: https://github.com/Azure/azure-sdk-for-python/pull/21696/files

**Comment by scbedd** [comment] 2021-11-12 19:06
This, to me, looks like something is being set wrong during `playback` in the python shim. It _looks_ like `x-upstream-uri` header isn't being set.

**Comment by scbedd** [comment] 2021-11-17 01:50
Ok. After digging, the reason that the `translation` API calls are failing is because they have an extra leading `/` in front of the path.

Your base-upstream-uri is set perfectly fine, but the actual request PATH looks like:

```
//translator/text/batch/v1.0/batches
```

Directly out of RawTarget. That extra leading slash is breaking our `Uri(<hostname>, <path>)`. Submitting a PR that addresses this, but I'm not certain we should.

**Comment by scbedd** [comment] 2021-11-17 21:07
Going to close this issue, Krista has confirmed that the update will come from azure-core.

I will re-open this issue (and the accompanying PR) if we need to correct these longer term.

**Closed** 2021-11-18 22:07 UTC
Labels: Central-EngSys
