### ISSUE TITLE
[Python APIView] Nested return type not displaying inner type

### ISSUE THREAD

**Issue by swathipil** [Azure/azure-sdk-tools#2540] opened 2022-01-12 22:53 UTC
In [this method](https://github.com/Azure/azure-sdk-for-python/blob/6807eb431ba79df48388927d788f34ab7efa1cdb/sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_receiver.py#L743) (and multiple others), the return type is defined as `List[ServiceBusReceivedMessage]`. However, the APIView only shows [`List`](https://apiview.dev/Assemblies/Review/fb319de65d2b4eca86b215c62d0cbe7b?diffRevisionId=aaf3f878ed3f47418e0452520cc08f74&doc=False&diffOnly=False#). I think it may have something to do with adding the type hint to the method signature. It did not display incorrectly before we updated to type hints in the method signature, rather than only in the docstring.

**Comment by tjprescott** [comment] 2022-01-12 23:09
@swathipil can you provide the link to the APIView?

**Comment by swathipil** [comment] 2022-01-13 00:16
yes it's here: https://apiview.dev/Assemblies/Review/fb319de65d2b4eca86b215c62d0cbe7b/76c6cea520e141c289728df4ad1aba84?doc=False

**Comment by tjprescott** [comment] 2022-01-13 16:36
And can you provide a link to the source code that is generating this? Copy-paste is fine too

**Comment by tjprescott** [comment] 2022-01-13 17:10
It looks like APIView 0.2.8 (which was merged yesterday) might fix your issue. I tried to repro in a unit test and it passed. But it's also possible that the code I'm looking at isn't what generated this.

**Comment by tjprescott** [comment] 2022-01-13 17:14
Well, I can repro this error the Python 3 typehint case.

**Comment by swathipil** [comment] 2022-01-13 17:16
This is the specific method that I was referring to, but there are other ones in this file as well that had the same issue: https://github.com/Azure/azure-sdk-for-python/blob/6807eb431ba79df48388927d788f34ab7efa1cdb/sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_receiver.py#L743

**Comment by tjprescott** [comment] 2022-01-13 17:19
Ah okay, well, yes, that does make sense then that you are seeing this. So the issue isn't Python 2 typehints at all, just the Python 3 ones. And it turns out this is the same regression due to breaking changes after Python 3.6 as (https://github.com/Azure/azure-sdk-tools/issues/2478). In the same way it started just generating "Optional", that is the same reason it is now just generating "List".

**Closed** 2022-01-14 18:36 UTC
Labels: APIView, Client, Python
