### ISSUE TITLE
Can't create an empty APIView report with a single diagnostic

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-sdk-tools#281] opened 2019-11-05 22:13 UTC
I tried to create a report with a single diagnostic, for when people uploaded the wrong file. Firstly, I generated the following json:

```json
{
  "Navigation" : [ ],
  "Name" : "azure-core-1.0.0-preview.6.jar",
  "Tokens" : [ ],
  "Diagnostics" : [ {
    "DiagnosticId" : "AZ_JAVA_1",
    "Text" : "Uploaded files should end with '-sources.jar', as the APIView tool only works with source jar files, not compiled jar files. The uploaded file that was submitted to APIView was named azure-core-1.0.0-preview.6.jar",
    "HelpLinkUri" : null,
    "TargetId" : ""
  } ]
}
```

But subsequently, I added a single token:

```json
{
  "Navigation" : [ ],
  "Name" : "azure-core-1.0.0-preview.6.jar",
  "Tokens" : [ {
    "DefinitionId" : "error",
    "NavigateToId" : null,
    "Kind" : 5,
    "Value" : "Error!"
  } ],
  "Diagnostics" : [ {
    "DiagnosticId" : "AZ_JAVA_1",
    "Text" : "Uploaded files should end with '-sources.jar', as the APIView tool only works with source jar files, not compiled jar files. The uploaded file that was submitted to APIView was named azure-core-1.0.0-preview.6.jar",
    "HelpLinkUri" : null,
    "TargetId" : "error"
  } ]
}
```

In either case, I ended up with an empty code area in the report, and no diagnostic warning message to the user.

**Comment by praveenkuttappan** [comment] 2021-11-05 17:49
Closing this issue since this is kind of duplicate of #448 Goal here is to add a UI option to notify failure reason.

**Closed by praveenkuttappan** 2021-11-05 17:49 UTC
Labels: APIView, Central-EngSys
