### ISSUE TITLE
[API view] Formatting issue in Java API view 

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk-tools#4052] opened 2022-09-01 21:33 UTC
https://apiviewstaging.azurewebsites.net/Assemblies/Review/9f0252f1f1264c61be1fe517a0d8d667

- The class annotation has additional space. 
- The class ending parenthesis indentation does not align with class declaration indentation
![image](https://user-images.githubusercontent.com/51379715/188016733-d5fac227-a416-4f4b-ab79-c856cc81c1c1.png)

**Comment by JonathanGiles** [comment] 2022-09-05 23:13
Looks to be a regression introduced by #3941

**Comment by Vailorium** [comment] 2022-09-20 22:10
@JonathanGiles

**Comment by Vailorium** [comment] 2022-10-03 01:35
This appears to be working fine on the main branch - it was probably resolved with #4091

**Comment by Vailorium** [comment] 2022-10-04 02:36
Issue is in the Java code, which I hadn't rebuilt since some changes were made. Reopened and looking into this again.

**Closed** 2022-10-04 04:08 UTC
Labels: APIView, massey-2022
