### ISSUE TITLE
[APIview] [Python] custom linter reporting duplicate errors

### ISSUE THREAD

**Issue by kristapratico** [Azure/azure-sdk-tools#3712] opened 2022-07-20 23:22 UTC
https://apiview.dev/Assemblies/Review/453e3478565f4bdfb4df7e8ca9b53ba9#azure.ai.textanalytics.AnalyzeHealthcareEntitiesAction

Specific example is the `__eq__` method on AnalyzeHealthcareEntitiesAction:

![image](https://user-images.githubusercontent.com/31998003/180098936-d6a61f26-bb17-4b22-9bd2-e3333f3f04e3.png)

**Comment by l0lawrence** [comment] 2022-07-20 23:50
Removing for now - will need to add in case/test

**Comment by tjprescott** [comment] 2022-07-21 22:59
@kristapratico are the warnings accurate? If so, can they be fixed? @johanste and @annatisch would like to move to the point where any warnings on APIViews are blocking anyhow.

**Comment by kristapratico** [comment] 2022-07-22 00:06
Fair point. Going to leave this open, though, so the duplicate errors can be fixed - it makes my browser want to explode.

**Comment by praveenkuttappan** [comment] 2022-08-01 18:33
@LibbaLawrence This issue is fixed in latest pylint-checker-guidelines. right?

**Comment by l0lawrence** [comment] 2022-08-01 18:46
Yes, it is still open so that it can be fixed if we want to enable this checker again.

**Comment by tjprescott** [comment] 2022-08-02 15:41
@l0lawrence is this an issue with APIView or the custom linter rule itself??

**Comment by l0lawrence** [comment] 2022-08-02 15:56
> @l0lawrence is this an issue with APIView or the custom linter rule itself??

I ran this locally and I only got the 3 warnings once, so I believe this is an APIView issue.

**Comment by tjprescott** [comment] 2022-08-02 16:18
If the warning is legitimate, I would argue we should definitely _not_ disable this checker. These warnings should be fixed. Disabling them from APIView circumvents that. I can look at the duplication next week, but fixing the issue in the code would resolve the warnings, and that is the course that should be taken.

**Comment by l0lawrence** [comment] 2022-08-02 20:12
> If the warning is legitimate, I would argue we should definitely _not_ disable this checker. These warnings should be fixed. Disabling them from APIView circumvents that. I can look at the duplication next week, but fixing the issue in the code would resolve the warnings, and that is the course that should be taken.

Let me double check with Krista that they are valid, and we can reinstate Docstring in version .7 with @Stevenjin8 's aiohttp/requests checker as well

**Comment by kristapratico** [comment] 2022-08-02 20:24
The linter warnings are valid and have since been fixed. The issue with the duplication is that it basically crashes the page making it hard to review the warnings present.

**Comment by tjprescott** [comment] 2022-08-08 21:39
![image](https://user-images.githubusercontent.com/5723682/183519240-572994cd-25c5-4a6b-97dc-2ff45285eda5.png)

So the issue is that a generated diagnostics is being repeatedly rendered on these methods, which points to an issue with the target ID not being specific enough.

**Comment by l0lawrence** [comment] 2022-08-09 16:32
> ![image](https://user-images.githubusercontent.com/5723682/183519240-572994cd-25c5-4a6b-97dc-2ff45285eda5.png)
> 
> So the issue is that a generated diagnostics is being repeatedly rendered on these methods, which points to an issue with the target ID not being specific enough.

By target ID do you mean the pylint node that the message is correlated with, or do you mean an ApiView target ID?

**Comment by tjprescott** [comment] 2022-08-09 21:10
The same logical issue (in this case AZ_PY_3) is being repeatedly associated with APIView target IDs. Hence, if this appears 10 times in the APIView, each one will appear to have 10 copies of the same diagnostic.

**Closed** 2022-08-10 23:41 UTC
Labels: APIView, Python
